# Generated by Django 4.1 on 2022-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0003_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="favourite",
            field=models.BooleanField(default=False),
        ),
    ]
