# Generated by Django 4.1 on 2022-11-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0005_remove_book_favourite"),
    ]

    operations = [
        migrations.RemoveField(model_name="favourite", name="favourite",),
    ]
