# Generated by Django 4.1 on 2022-11-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0007_book_favourite"),
    ]

    operations = [
        migrations.DeleteModel(name="Favourite",),
    ]
