# Generated by Django 4.1 on 2022-11-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0010_comment_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="book_id", field=models.IntegerField(default=-1),
        ),
    ]
