# Generated by Django 4.1 on 2022-11-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0011_alter_comment_book_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book", name="rate", field=models.IntegerField(default=0),
        ),
    ]
